version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: go dependencies
          command: |
            sudo apt-get update
            sudo apt-get install golang
      - run:
          name: go path
          command: |
            echo 'export GOPATH="$HOME/go"' >> $BASH_ENV
      - run:
          name: unit tests
          command: |
            bash ./codeship/unit_tests.sh
