version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest  # pins image to specific version using YYYY-MM format    
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: go dependencies
          command: |
            sudo go get github.com/Sirupsen/logrus
      - run:
          name: unit tests
          command: |
            bash ./codeship/unit_tests.sh

